name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y rpm

    - name: Configure
      run: cmake -S. -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Create DEB & RPM packages
      run: |
        cd build
        cpack -G DEB
        cpack -G RPM

    - name: Archive source code
      run: |
        git archive --format=zip --output=source.zip HEAD
        git archive --format=tar.gz --output=source.tar.gz HEAD

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: |
          build/*.deb
          build/*.rpm
          source.zip
          source.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -S. -B build -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: Create MSI package
      run: |
        cd build
        cpack -G WIX

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-package
        path: build/*.msi

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -S. -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Create DMG package
      run: |
        cd build
        cpack -G DragNDrop

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-package
        path: build/*.dmg

  create-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List downloaded files
      run: find artifacts -type f

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          artifacts/linux-packages/*.deb
          artifacts/linux-packages/*.rpm
          artifacts/linux-packages/*.zip
          artifacts/linux-packages/*.tar.gz
          artifacts/windows-package/*.msi
          artifacts/macos-package/*.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
